### PR TITLE
refactor: add fluid typography, responsiveness and major refactoring

### PR DESCRIPTION
**Pull request by TejasShekar**
UI has been improved.
Added fluid typography.
Fixed broken layouts.
Added responsiveness as well.

Preview Link : https://deploy-preview-32--prime8-ui.netlify.app/

### CODE REVIEW

**Review by rishbitsnbytes — APPROVED** [review]
Code looks clean and good to merge!

**Review by MaruthiPothuganti — APPROVED** [review]
Refactored well . Everything looks Good. PR can be merged

**Review by rishbitsnbytes — APPROVED** [review]
Everything looks clean and good to merge!

**Comment by TejasShekar** [comment]
Thankyou for reviewing such a massive and long awaited PR that I was working on and off over the last 6 months. @MaruthiPothuganti @rishbitsnbytes

**Pull request merged**
